### ISSUE TITLE
MongoDB command used to get collections deprecated in 3.0

### ISSUE THREAD

**Issue by paulwalker** [DatabaseCleaner/database_cleaner-mongo#3]
http://docs.mongodb.org/manual/reference/system-collections/

need to use listCollections command in 3+.

http://docs.mongodb.org/manual/reference/command/listCollections/#dbcmd.listCollections

**Comment by etagwerker** [comment]
I don't think this issue is present in this adapter. I see that now we are getting collections like this: https://github.com/DatabaseCleaner/database_cleaner-mongo/blob/master/lib/database_cleaner/mongo/truncation.rb#L53
